apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: user-registration
spec:
  selector:
    app: client
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001  # Access from outside cluster
  type: NodePort